import type {
  DexPair,
  FearGreedSnapshot,
  MarketAsset,
  NewsItem,
} from "@/server/types/domain";
import type { AssetSymbol } from "@/types";

const now = () => new Date().toISOString();

export const mockMarketAssets: MarketAsset[] = [
  {
    id: "bitcoin",
    symbol: "BTC",
    name: "Bitcoin",
    priceUsd: 103420,
    priceChange24h: 2.8,
    priceChange7d: 6.4,
    volume24hUsd: 42100000000,
    marketCapUsd: 2040000000000,
    rank: 1,
    source: "mock",
  },
  {
    id: "ethereum",
    symbol: "ETH",
    name: "Ethereum",
    priceUsd: 5480,
    priceChange24h: 1.2,
    priceChange7d: 4.1,
    volume24hUsd: 23900000000,
    marketCapUsd: 660000000000,
    rank: 2,
    source: "mock",
  },
  {
    id: "solana",
    symbol: "SOL",
    name: "Solana",
    priceUsd: 214,
    priceChange24h: 7.9,
    priceChange7d: 12.3,
    volume24hUsd: 6100000000,
    marketCapUsd: 101000000000,
    rank: 5,
    source: "mock",
  },
  {
    id: "ondo-finance",
    symbol: "ONDO",
    name: "Ondo Finance",
    priceUsd: 1.84,
    priceChange24h: 13.6,
    priceChange7d: 28.2,
    volume24hUsd: 782000000,
    marketCapUsd: 5900000000,
    rank: 64,
    source: "mock",
  },
  {
    id: "aerodrome-finance",
    symbol: "AERO",
    name: "Aerodrome Finance",
    priceUsd: 1.42,
    priceChange24h: -6.4,
    priceChange7d: 9.5,
    volume24hUsd: 188000000,
    marketCapUsd: 1180000000,
    rank: 148,
    source: "mock",
  },
  {
    id: "arbitrum",
    symbol: "ARB",
    name: "Arbitrum",
    priceUsd: 1.18,
    priceChange24h: -3.2,
    priceChange7d: -8.1,
    volume24hUsd: 445000000,
    marketCapUsd: 5200000000,
    rank: 71,
    source: "mock",
  },
];

export const mockDexPairs: DexPair[] = [
  {
    chainId: "ethereum",
    dexId: "uniswap",
    pairAddress: "mock-btc-usdc",
    baseSymbol: "BTC",
    baseName: "Wrapped Bitcoin",
    quoteSymbol: "USDC",
    priceUsd: 103380,
    volume24hUsd: 248000000,
    liquidityUsd: 92000000,
    txns24h: 13320,
    priceChange24h: 2.6,
    source: "mock",
  },
  {
    chainId: "base",
    dexId: "aerodrome",
    pairAddress: "mock-aero-usdc",
    baseSymbol: "AERO",
    baseName: "Aerodrome Finance",
    quoteSymbol: "USDC",
    priceUsd: 1.42,
    volume24hUsd: 87000000,
    liquidityUsd: 31000000,
    txns24h: 22940,
    priceChange24h: -6.4,
    source: "mock",
  },
  {
    chainId: "ethereum",
    dexId: "uniswap",
    pairAddress: "mock-ondo-usdc",
    baseSymbol: "ONDO",
    baseName: "Ondo Finance",
    quoteSymbol: "USDC",
    priceUsd: 1.84,
    volume24hUsd: 261000000,
    liquidityUsd: 44000000,
    txns24h: 18480,
    priceChange24h: 13.6,
    source: "mock",
  },
];

export const mockNews: NewsItem[] = [
  {
    id: "news-rwa-flows",
    title: "RWA tokens rally as tokenized treasury flows accelerate",
    url: "https://example.com/rwa-flows",
    source: "Alpha Mock News",
    publishedAt: now(),
    currencies: ["ONDO"],
    sentiment: "bullish",
    votes: { positive: 48, negative: 4, important: 22 },
  },
  {
    id: "news-l2-fees",
    title: "Layer 2 activity cools while traders rotate into base ecosystem liquidity",
    url: "https://example.com/l2-fees",
    source: "Alpha Mock News",
    publishedAt: now(),
    currencies: ["ARB", "AERO", "ETH"],
    sentiment: "neutral",
    votes: { positive: 21, negative: 18, important: 15 },
  },
  {
    id: "news-sol-meme-volume",
    title: "Solana meme coin volume jumps, pushing DEX transactions higher",
    url: "https://example.com/sol-volume",
    source: "Alpha Mock News",
    publishedAt: now(),
    currencies: ["SOL"],
    sentiment: "bullish",
    votes: { positive: 38, negative: 11, important: 19 },
  },
];

export const mockFearGreed: FearGreedSnapshot = {
  value: 71,
  classification: "Greed",
  timestamp: now(),
  previousValue: 63,
  source: "mock",
};

export function mockNewsForAsset(asset: AssetSymbol) {
  return mockNews.filter((item) => item.currencies.includes(asset));
}
